# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.100
    - name: Change Directory 
      run: cd $GITHUB_WORKSPACE/src
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Change Directory 
      run: cd $GITHUB_WORKSPACE/test      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Change Directory
      run: cd $GITHUB_WORKSPACE/src    
    - name: Build Docker image
      run: docker build -t yourdockerhubusername/yourimagename:latest .
      working-directory: ${{ github.workspace }}
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/super-service:latest      
